// This file is auto-generated by a script. Do not edit directly.
// It contains constants for the configuration keys from package.json.
// Update with npm run config

export const BUILDFILE = "buildFile";
export const NOTIFYCHANGE = "notifyChange";
export const MAXPACKAGESIZE = "maxPackageSize";
export const MAXCACHESIZE = "maxCacheSize";
export const ENABLEDELETION = "enableDeletion";
export const ENABLEADDITION = "enableAddition";
export const EXCLUDEDEPENDENCIES = "excludeDependencies";
export const BAZELSHUTDOWNONACTIVATION = "bazelShutdownOnActivation";
export const FIXDEPSONCURRENT = "fixDepsOnCurrent";
export const KINDPATTERN = "kindPattern";
export const IMPORTPATHREPLACEMENTS = "importPathReplacements";
export const DEFAULTROOT = "defaultRoot";

// A union type of all possible configuration keys.
export type ConfigKey = "buildFile" | "notifyChange" | "maxPackageSize" | "maxCacheSize" | "enableDeletion" | "enableAddition" | "excludeDependencies" | "bazelShutdownOnActivation" | "fixDepsOnCurrent" | "kindPattern" | "importPathReplacements" | "defaultRoot";
